name: Release
description: "Release"
inputs:
  COMMAND:
    description: 'command argument'
    required: true
  network:
    description: 'Release network environment'
    default: 'internal'
  rc_number:
    description: 'Rc number (e.g. 100310)'
  deploy_number:
    description: 'Deploy number (e.g. 1)'
  launcher_commit:
    description: 'Specific launcher commit'
  player_commit:
    description: 'Specific player commit'
  ENV:
    description: 'Environment'
    default: 'test'
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  SLACK_TOKEN:
    description: 'SLACK_TOKEN'
    required: true
  SLACK_CHANNEL:
    description: 'SLACK_CHANNEL'
    required: true
  KEY_PASSPHRASE:
    description: 'KEY_PASSPHRASE'
    required: true
  KEY_ADDRESS:
    description: 'KEY_ADDRESS'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'