name: Prepare Release
description: "Prepare Release"
inputs:
  network:
    description: 'Release network environment'
    default: 'internal'
  rc-number:
    description: 'Rc number (e.g. 100310)'
  deploy-number:
    description: 'Deploy number (e.g. 1)'
  sign:
    description: 'Code signing'
    default: 'false'
  launcher-commit:
    description: 'Specific launcher commit'
  player-commit:
    description: 'Specific player commit'
  ENV:
    description: 'Environment'
    default: 'test'
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  SLACK_TOKEN:
    description: 'SLACK_TOKEN'
    required: true
  KEY_PASSPHRASE:
    description: 'KEY_PASSPHRASE'
    required: true
  KEY_ADDRESS:
    description: 'KEY_ADDRESS'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.network }}