name: Release
description: "Release"
inputs:
  COMMAND_LIST:
    description: 'command argument'
    required: true
  ENV:
    description: 'Environment'
    default: 'test'
runs:
  using: 'docker'
  env:
    COMMAND_LIST: ${{ inputs.COMMAND_LIST }}
    ENV: ${{ inputs.ENV }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
    KEY_PASSPHRASE: ${{ secrets.KEY_PASSPHRASE }}
    KEY_ADDRESS: ${{ secrets.KEY_ADDRESS }}
    KEY_PRIVATE: ${{ secrets.KEY_PRIVATE }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    ESIGNER_CREDENTIAL_ID: ${{ secrets.ESIGNER_CREDENTIAL_ID }}
    ESIGNER_USERNAME: ${{ secrets.ESIGNER_USERNAME }}
    ESIGNER_PASSWORD: ${{ secrets.ESIGNER_PASSWORD }}
    ESIGNER_TOTP_SECRET: ${{ secrets.ESIGNER_TOTP_SECRET }}
  image: 'Dockerfile'
